### ISSUE TITLE
[JOSS] Minor Paper Formatting

### ISSUE THREAD

**Issue by amritagos** [giorginolab/plumed2-pycv#1]
Part of https://github.com/openjournals/joss-reviews/issues/1773. The phrase changes are suggestions, and similar grammatical updates will be considered. Please fix the following minor issues with the manuscript:
## Paragraph I
![image](https://user-images.githubusercontent.com/32496815/66309529-7f490900-e927-11e9-97fa-3b12e064e55e.png)
Double spacing in the first paragraph.
## Paragraph II
- "occupies a large fraction of the effort in the exploration.." -> "accounts for most of the efforts associated with the exploration..."
- "biasing libraries" --> Intent unclear. PLUMED is a library which includes enhanced sampling techniques for steered or 'biased' MD, but clarification is required.
- 'which provides' --> Unclear, sentence structure makes it seem like it refers to the "biasing libraries" when it appears to have been intended for PLUMED (suggestion: refactor sentence)
## Code
![image](https://user-images.githubusercontent.com/32496815/66310125-0480ed80-e929-11e9-8916-4fc5fc0eeb11.png)
- CV function is actually called
## Conclusions
- Since these are important conclusions, it might be better to spread them out as a numbered list, one per line.

**Comment by tonigi** [comment]
Thanks! Changes are in b5bb113a0bf20709c97df1998689072951b17e6a , and in particular

* Double space changed in source: However it may not reflect in the output because the spacing is in control of the typesetting engine. (Latex's spacing rules for intersentence space)
* Paragraph II: rewritten
* Code: reworded as "PLUMED will call the following function"
* Conclusions: itemized as requested.

**Comment by amritagos** [comment]
Thanks for the prompt resolution!
